### ISSUE TITLE
'weight' attribute of dataset

### ISSUE THREAD

**Issue by BlockChanZJ** [BorgwardtLab/filtration_curves#1]
Thanks for your excellent works!
Can you provide the raw data url of dataset?
There is an attribute called 'weight' in MUTAG data, and it is different from [TUDataset](https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets), how do you reweight it?
I tried OllivierRicci method, but there answer is not as good as yours.
Thanks again!

**Comment by lobray** [comment]
Thank you for flagging this. We did use the MUTAG data from the TUDataset (the one provided in the repo already has edge weights added). I looked into the issue and it's due to some changes in the `GraphRicciCurvature` package from June 9. I checked, and if you fix the version to `GraphRicciCurvature = "0.5.2.1,"` you will replicate the results we have. I'll update the `pyproject.toml` so that the version is correct.
